# Page settings
baseurl = "localhost:1313"
title = "Passpill Project"
languageCode = "en-us"
theme = "passpill-theme"

[params]

  custom_css = ["css/index.css"]

  # Meta
  author = "Javier Marquez - http://arqex.com"
  description = ""
  email = ""

  # Navigation
  [params.navigation]
    home = "Home"
    work = "Work"
    testimonials = "Testimonials"
    services = "Services"
    about = "About"
    contact = "Contact"


  # Contact section
  [params.contact]
    enable = true
    map = false
    form = true
    title = "Get in touch"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Passpill Project'


  # markdown options
  [blackfriday]
    # Transform \n into <br>
    extensions=["hardLineBreak"]

  [OpenGraph]
    hide = true
